replicaCount: 1

image:
  repository: vllm/vllm-openai
  tag: v0.7.2
  pullPolicy: IfNotPresent

model: /home/tonydja/projets/data/llm/llama-3-8B-instruct-quantized.w8a16
port: 8000

resources:
  limits:
    cpu: 4

service:
  type: ClusterIP
  port: 80