replicaCount: 1

image:
  repository: vllm-cpu
  tag: latest
  pullPolicy: Never

model: /home/tonydja/projets/data/llm/llama-3-8B-instruct-quantized.w8a16
port: 8000

resources:
  limits:
    cpu: 4

service:
  type: ClusterIP
  port: 80