apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vllm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-vllm
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-vllm
    spec:
      containers:
        - name: vllm
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Never
          args:
            - "--model"
            - "{{ .Values.model }}"
            - "--port"
            - "{{ .Values.port }}"
            - "--device"
            - "cpu"
#            - "--gpu-memory-utilization"
#            - "0.90"
          ports:
            - containerPort: {{ .Values.port }}
          resources:
            limits:
              {{- toYaml .Values.resources.limits | nindent 14 }}
