apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-vllm
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-vllm
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.port }}
